{
 "title": "My Troubleshooting Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{application=\"troubleshootingApp\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время запросов к URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{application=\"troubleshootingApp\"}[5m])) / sum by(uri) (rate(http_server_requests_seconds_count{application=\"troubleshootingApp\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активность сборщика мусора",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование памяти JVM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"troubleshootingApp\", area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}